### ISSUE TITLE
Misconfigured mailto link 

### ISSUE THREAD

**Issue by ghost** [gonum/old-website#11] opened 2017-09-22 06:56 UTC
On the first page the link to the google group is 
"mailto:https://groups.google.com/forum/#!forum/gonum-dev"
causing it to open my email client instead of linking to the page. 

This is probably caused by the email being configured to be that link and the page being set up to auto generate link.

**Comment by kortschak** [comment] 2017-09-22 08:18
There are four things we can do:

1. Use the gonum-dev@googlegroups.com email address (this may lead people astray in that they won't necessarily receive replies).
2. Not use the contact widget and use the custom widget (this does not have the mail icon).
3. Don't use `autolink=true` in `contact.md` (this means people need to copy-paste the link).
4. File an issue against github.com/gcushen/hugo-academic to allow this kind of use (an additional configuration tag in `contact.md`'s toml header and necessary wiring to get [this part](https://github.com/gcushen/hugo-academic/blob/690ed4d31438a2e43ff2646765c701caba78071d/layouts/partials/widgets/contact.html#L20) of the contact partial to work. (It would be nice if the template could automagically know not to change a scheme, but that requires more work).

I think 4. is the best option, but depends on @gcushen accepting the issue and PR.

**Comment by btracey** [comment] 2017-09-22 13:22
We can’t do 1 without more changes. Currently we whitelist individuals who can post on the mailing list to avoid spam.

**Comment by kortschak** [comment] 2017-10-29 22:34
See https://github.com/gcushen/hugo-academic/issues/351#issuecomment-340299553

**Comment by han-so1omon** [comment] 2020-05-23 04:31
The issue as noted by @emilejby is no longer true. The email icon correctly links to the Google Group. If the purpose of the icon is to allow for new devs to join, then it serves its purpose. Otherwise, it is simple enough to contact the dev team via github.

**Comment by kortschak** [comment] 2020-05-23 04:35
The issue is at the bottom of the page; academic make the link a `mailto:` scheme.

**Comment by kortschak** [comment] 2020-06-20 09:43
Fixed with new website build.

**Closed as completed by kortschak** 2020-06-20 09:43 UTC
